services:
  web:
    image: 127.0.0.1:5000/swarm-playground-web
    build: web
    ports:
      - "8080:8080"
    environment:
      MANAGEMENT_ELASTIC_METRICS_EXPORT_HOST: https://elastic:9200
  backend:
    image: 127.0.0.1:5000/swarm-playground-backend
    build: backend
    deploy:
      replicas: 2
    environment:
      REPLICA: "{{.Task.Slot}}"
      MANAGEMENT_ELASTIC_METRICS_EXPORT_HOST: https://elastic:9200

  mongo:  # for now for Spring Session
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: swarm-playground

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb@mongo:27017/

# monitoring part, based on https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  kibana:
    depends_on:
      - elastic
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
