services:
  web:
    image: 127.0.0.1:5000/swarm-playground-web
    build: web
    ports:
      - "8080:8080"
    environment:
      MANAGEMENT_ELASTIC_METRICS_EXPORT_HOST: https://elasticsearch:9200
    networks:
      - elk
  backend:
    image: 127.0.0.1:5000/swarm-playground-backend
    build: backend
    deploy:
      replicas: 2
    environment:
      REPLICA: "{{.Task.Slot}}"
      MANAGEMENT_ELASTIC_METRICS_EXPORT_HOST: https://elasticsearch:9200
    networks:
      - elk

  mongo:  # for now for Spring Session
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: swarm-playground

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb@mongo:27017/
