spring:
  data:
    mongodb:
      username: root
      password: mongodb
      host: mongo
      database: swarm-playground
      authentication-database: admin
  session:
    mongodb:
      collection-name: sessions
#server:
#  port: 8082
management:
  elastic:
    metrics:
      export:
        enabled: true
        step: 1m
        index: micrometer-metrics
