spring:
  data:
    mongodb:
      username: root
      password: mongodb
      host: mongo
      database: swarm-playground
      authentication-database: admin
  session:
    mongodb:
      collection-name: sessions
